logging:
  level:
    org.springframework: WARN
---
spring:
  jpa:
    database: H2
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: false
        use_sql_comments: true
  datasource:
    url: jdbc:h2:file:./data/data
    driverClassName: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true